### ISSUE TITLE
Plugin prevents kibana 4.5 from starting

### ISSUE THREAD

**Issue by digitalrinaldo** [sirensolutions/kibi-wordcloud-plugin#2]
Downloaded and built the plugin, installed it as wordcloud not as directions indicated. The directions for manual install do not account for version number.  In any case if the plugin is present kibana 4.5 doesn't start.

**Comment by scampi** [comment]
this plugin was not yet tested with kibana 4.5. It will be with the next release of kibi.

**Comment by scampi** [comment]
@digitalrinaldo I tested the plugin with Kibana 4.5.3 and it worked fine. Please open an issue if you still have problems with reproducible steps and some logs/stacktraces if you have any.
