### ISSUE TITLE
Update for Kibana 5.0?

### ISSUE THREAD

**Issue by OzWookiee** [sirensolutions/kibi-wordcloud-plugin#6]
Just wondering if you're going to be updating to support Kibana 5.0

**Comment by scampi** [comment]
We haven't yet started working on 5.0 but depending on when kibana's own [tag cloud](https://github.com/elastic/kibana/issues/8149) gets merged, this visualization might get deprecated.

**Comment by OzWookiee** [comment]
Oh nice, thanks for the link!
